/** MIT verification; Playwright Apache-2.0; model notices in public/anatomy-final/credits.txt. */
const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs/promises');
(async()=>{const out='/tmp/medica-anatomy-verification';await fs.mkdir(out,{recursive:true});const browser=await chromium.launch({headless:true,args:['--enable-webgl','--use-gl=angle','--use-angle=metal']});try{
 const page=await browser.newPage({viewport:{width:1280,height:900}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
 const data=()=>page.locator('[data-testid="anatomy-canvas"]').evaluate(e=>({...e.dataset}));
 await page.goto('http://127.0.0.1:3100/anatomy-final');await page.waitForFunction(()=>+document.querySelector('[data-testid="anatomy-canvas"]')?.dataset.firstInteractiveMs>0,null,{timeout:120000});
 const startup=await data();await page.screenshot({path:out+'/desktop-skeleton.png'});console.log('STARTUP',startup);
 for(const name of ['Nervous','Respiratory','Muscular']){await page.getByRole('button',{name:'Show only '+name,exact:true}).click();await page.waitForTimeout(3500);await page.screenshot({path:out+'/'+name.toLowerCase()+'.png'});console.log(name,await data());}
 await page.getByRole('button',{name:'Show only Skeletal',exact:true}).click();await page.keyboard.press('Control+k');assert(await page.getByRole('searchbox').evaluate(e=>e===document.activeElement));await page.getByRole('searchbox').fill('mandible');await page.locator('.af-results button').first().click();await page.waitForSelector('.af-selection');await page.waitForFunction(()=>document.querySelector('.af-detail-status')?.textContent.includes('Source-resolution'),null,{timeout:120000});await page.screenshot({path:out+'/mandible-detail.png'});await page.getByRole('button',{name:'Clear isolation',exact:true}).click();await page.getByRole('searchbox').fill('');
 for(const button of await page.locator('.af-system').all())if(await button.getAttribute('aria-pressed')==='false')await button.click();
 await page.waitForFunction(()=>document.querySelector('[data-testid="anatomy-canvas"]')?.dataset.loadedSystems==='11',null,{timeout:120000});await page.waitForTimeout(500);const exterior=await data();await page.screenshot({path:out+'/exterior.png'});
 await page.locator('[data-system="integumentary"] .af-system').click();await page.waitForTimeout(500);const all=await data();await page.screenshot({path:out+'/internal-systems.png'});
 await page.locator('#af-explode').focus();await page.keyboard.press('End');await page.waitForSelector('.af-study-tile');await page.waitForTimeout(500);const board=await data();await page.screenshot({path:out+'/study-desktop.png'});
 const scroll=page.locator('.af-board-scroll');await scroll.evaluate(e=>e.scrollTop=500);await page.waitForTimeout(300);const before=await scroll.evaluate(e=>e.scrollTop);await page.locator('.af-study-tile').filter({visible:true}).nth(10).click();await page.waitForSelector('.af-selection');await page.getByRole('button',{name:'Return to study board'}).click();assert.equal(await scroll.evaluate(e=>e.scrollTop),before);
 const layouts=[];for(const width of [960,395]){await page.setViewportSize({width,height:width===395?844:720});await scroll.evaluate(e=>e.scrollTop=0);await page.waitForTimeout(500);const layout=await page.locator('.af-credits').evaluate(e=>{const r=e.getBoundingClientRect();return {top:r.top,bottom:r.bottom,height:innerHeight,overflow:document.documentElement.scrollWidth>innerWidth};});assert(layout.top>=0&&layout.bottom<=layout.height+1&&!layout.overflow);layouts.push({width,...layout,metrics:await data()});await page.screenshot({path:out+'/study-'+width+'.png'});}
 await page.emulateMedia({reducedMotion:'reduce'});await page.locator('#af-explode').focus();await page.keyboard.press('Home');await page.waitForTimeout(1000);const idle=await data();await page.waitForTimeout(600);assert.equal((await data()).renderFrames,idle.renderFrames);
 const timing=await page.evaluate(async()=>{const a=[];let last=performance.now();const c=document.querySelector('canvas');c.focus();for(let i=0;i<60;i++)await new Promise(r=>requestAnimationFrame(t=>{a.push(t-last);last=t;c.dispatchEvent(new KeyboardEvent('keydown',{key:'ArrowRight',bubbles:true}));r();}));return a.sort((a,b)=>a-b);});
 const memory=await page.evaluate(()=>performance.memory?{usedJSHeapSize:performance.memory.usedJSHeapSize,totalJSHeapSize:performance.memory.totalJSHeapSize}:null);
 const resources=await page.evaluate(()=>performance.getEntriesByType('resource').map(e=>({name:e.name,encodedBodySize:e.encodedBodySize,transferSize:e.transferSize,duration:e.duration})));
 const range=await page.request.get('http://127.0.0.1:3100/anatomy-final/atlas/skeletal.glb',{headers:{Range:'bytes=0-19'}});assert.equal(range.status(),206);assert.equal((await range.body()).length,20);
 await page.setViewportSize({width:1280,height:900});await page.getByRole('link',{name:'Organ library'}).click();await page.waitForURL('**/anatomy');assert.equal(await page.locator('.anatomy-final canvas').count(),0);
 const failure=await browser.newPage();let fail=true;await failure.route('**/atlas/skeletal.glb',r=>{if(fail){fail=false;return r.fulfill({status:503,body:'retry'});}return r.continue();});await failure.goto('http://127.0.0.1:3100/anatomy-final');await failure.getByRole('button',{name:'Retry Skeletal'}).click({timeout:60000});await failure.waitForFunction(()=>+document.querySelector('[data-testid="anatomy-canvas"]')?.dataset.firstInteractiveMs>0,null,{timeout:60000});await failure.close();
 assert.deepEqual(errors,[]);const result={startup,exterior,all,board,layouts,memory,frames:{medianMs:timing[30],p95Ms:timing[57],maxMs:timing.at(-1)},resources,errors,checks:['11 systems','system-only views','mandible detail','keyboard search','board reversal and position restoration','395px board and persistent credits','reduced motion','idle rendering stops','range 206','load failure retry','route disposal']};await fs.writeFile('docs/anatomy-final/browser-results.json',JSON.stringify(result,null,2));console.log(JSON.stringify({...result,resources:resources.length},null,2));
 }finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1);});
