/** SPDX-License-Identifier: MIT. HRA FTU SVGs remain CC-BY-4.0. */
'use client';import {useEffect,useRef,useState} from 'react';import type {LessonDiagram} from './types';import styles from './lesson.module.css';
export function Microscopy({diagrams}:{diagrams:LessonDiagram[]}){const [active,setActive]=useState(diagrams[0]?.id),[group,setGroup]=useState(''),[zoom,setZoom]=useState(1);const object=useRef<HTMLObjectElement>(null),stage=useRef<HTMLDivElement>(null),drag=useRef<{x:number;y:number;left:number;top:number}|null>(null);const diagram=diagrams.find(x=>x.id===active)||diagrams[0];
 useEffect(()=>{setActive(diagrams[0]?.id);setGroup('');setZoom(1);},[diagrams]);
 useEffect(()=>{const document=object.current?.contentDocument;if(!document||!diagram)return;for(const g of diagram.groups)for(const id of g.elementIds){const e=document.getElementById(id) as SVGElement|null;if(e)e.style.opacity=group&&g.id!==group?'.18':'1';}},[group,diagram]);
 if(!diagram)return <p>Microscopic reference unavailable.</p>;
 return <div className={styles.micro}><div className={styles.microHeader}><div><h2>Microscopic anatomy</h2><p>Expert-reviewed HRA illustration · representative tissue unit, not a patient scan</p></div><div className={styles.segment}>{diagrams.map(d=><button key={d.id} className={d.id===active?styles.active:''} onClick={()=>{setActive(d.id);setGroup('');setZoom(1);}}>{d.id==='renal-corpuscle'?'Renal corpuscle':d.id==='nephron'?'Nephron':'Glandular acinus'}</button>)}</div></div>
 <div className={styles.microControls}><button onClick={()=>setZoom(v=>Math.max(1,v-.25))} aria-label="Zoom diagram out">−</button><output>{Math.round(zoom*100)}%</output><button onClick={()=>setZoom(v=>Math.min(4,v+.25))} aria-label="Zoom diagram in">+</button><button onClick={()=>{setZoom(1);if(stage.current){stage.current.scrollLeft=0;stage.current.scrollTop=0;}}}>Reset</button></div>
 <div className={styles.microBody}><div ref={stage} className={styles.microStage} onPointerDown={e=>{if(!stage.current)return;drag.current={x:e.clientX,y:e.clientY,left:stage.current.scrollLeft,top:stage.current.scrollTop};stage.current.setPointerCapture(e.pointerId);}} onPointerMove={e=>{if(!drag.current||!stage.current)return;stage.current.scrollLeft=drag.current.left-(e.clientX-drag.current.x);stage.current.scrollTop=drag.current.top-(e.clientY-drag.current.y);}} onPointerUp={()=>{drag.current=null;}}><object ref={object} key={diagram.url} data={diagram.url} type="image/svg+xml" aria-label={`${diagram.id} source illustration`} style={{width:`${zoom*100}%`,maxWidth:'none'}} onLoad={()=>setGroup(g=>g)}><p>Diagram unavailable. Use the structure list and source link.</p></object></div><div className={styles.microList}><h3>Structure and cell groups</h3>{diagram.groups.map(g=><button key={g.id} className={group===g.id?styles.active:''} onClick={()=>setGroup(group===g.id?'':g.id)} aria-pressed={group===g.id}>{g.label||g.id.replaceAll('_',' ')}</button>)}</div></div>
 <p className={styles.sourceFoot}>Source: <a href={`https://doi.org/${diagram.doi}`} target="_blank" rel="noreferrer">HRA {diagram.id} ↗</a> · <a href="/anatomy-final/lessons/credits.txt">CC-BY 4.0 and full credit ↗</a></p></div>;
}
