/** SPDX-License-Identifier: MIT. Imported HRA geometry/materials retain CC-BY-4.0. Three.js is MIT. */
import {ACESFilmicToneMapping,AmbientLight,Box3,Color,DirectionalLight,Group,Mesh,MeshStandardMaterial,PerspectiveCamera,Plane,PMREMGenerator,Raycaster,Scene,Vector2,Vector3,WebGLRenderer} from 'three';
import {OrbitControls} from 'three/examples/jsm/controls/OrbitControls.js';
import {GLTFLoader} from 'three/examples/jsm/loaders/GLTFLoader.js';
import {RoomEnvironment} from 'three/examples/jsm/environments/RoomEnvironment.js';
import type {LessonManifest,LessonStructure} from './types';
export class OrganLessonScene{
 private scene=new Scene();private camera=new PerspectiveCamera(38,1,.001,10);private renderer:WebGLRenderer;private controls:OrbitControls;private loader=new GLTFLoader();private roots:Group[]=[];private meshes=new Map<string,Mesh>();private index=new Map<string,LessonStructure>();private frame=0;private abort=new AbortController();private disposed=false;private resizeObserver:ResizeObserver;private reduced=matchMedia('(prefers-reduced-motion: reduce)');private raycaster=new Raycaster();private pointer=new Vector2();private downAt={x:0,y:0};private selected='';private groups=new Set<string>();private clipping=false;private reverse=false;private cut=0;private axis=new Vector3(0,1,0);private plane=new Plane(new Vector3(0,1,0),0);private bounds=new Box3();private environment;
 constructor(private host:HTMLElement,private manifest:LessonManifest,private onSelect:(structure:LessonStructure|null)=>void,private onStatus:(status:string)=>void){
  for(const s of manifest.structures)this.index.set(s.assetId+':'+s.nodeName,s);
  this.groups=new Set(manifest.id==='kidney'?['Capsule']:['Peripheral zone','Central zone','Transition zone','Anterior fibromuscular stroma']);
  this.renderer=new WebGLRenderer({antialias:true,powerPreference:'high-performance'});this.renderer.setPixelRatio(Math.min(devicePixelRatio,host.clientWidth<640?1.5:2));this.renderer.setClearColor(new Color('#0B1016'));this.renderer.toneMapping=ACESFilmicToneMapping;this.renderer.localClippingEnabled=true;host.append(this.renderer.domElement);
  this.camera.position.set(0,0,1);this.controls=new OrbitControls(this.camera,this.renderer.domElement);this.controls.enableDamping=!this.reduced.matches;this.controls.dampingFactor=.12;this.controls.addEventListener('change',this.invalidate);this.controls.addEventListener('start',this.invalidate);
  this.scene.add(new AmbientLight(0xffffff,.45));const key=new DirectionalLight(0xffffff,1.5);key.position.set(2,3,4);this.scene.add(key);const fill=new DirectionalLight(0xcde8ed,.55);fill.position.set(-2,1,-3);this.scene.add(fill);
  const pmrem=new PMREMGenerator(this.renderer),room=new RoomEnvironment();this.environment=pmrem.fromScene(room);this.scene.environment=this.environment.texture;room.dispose();pmrem.dispose();
  this.resizeObserver=new ResizeObserver(this.resize);this.resizeObserver.observe(host);this.renderer.domElement.addEventListener('pointerdown',this.pointerDown);this.renderer.domElement.addEventListener('click',this.click);this.reduced.addEventListener('change',this.motion);document.addEventListener('visibilitychange',this.visibility);this.resize();
 }
 async load(){const generation=this.abort.signal;try{for(let i=0;i<this.manifest.modelAssets.length;i++){const a=this.manifest.modelAssets[i];this.onStatus(`Loading ${a.id}…`);const response=await fetch(a.url,{signal:generation});if(!response.ok)throw Error(`Download failed (${response.status})`);const bytes=await response.arrayBuffer();if(generation.aborted)return;const gltf=await this.loader.parseAsync(bytes,'');if(generation.aborted||this.disposed){gltf.scene.traverse(o=>{if(o instanceof Mesh){o.geometry.dispose();const list=Array.isArray(o.material)?o.material:[o.material];for(const m of list)m.dispose();}});return;}const root=gltf.scene;root.updateMatrixWorld(true);this.roots.push(root);this.scene.add(root);root.traverse(o=>{if(!(o instanceof Mesh))return;const s=this.index.get(a.id+':'+o.name);if(!s)throw Error('Unmapped source node '+o.name);const original=Array.isArray(o.material)?o.material:[o.material];const clones=original.map(m=>m.clone() as MeshStandardMaterial);o.material=Array.isArray(o.material)?clones:clones[0];o.userData.lessonId=s.id;this.meshes.set(s.id,o);});this.setGroups([...this.groups]);if(i===0){this.bounds.setFromObject(root);this.fit(this.bounds);}this.onStatus(`${i+1}/${this.manifest.modelAssets.length} source models ready`);}this.onStatus('Source models ready · Medica review pending');}catch(e){if(!generation.aborted)this.onStatus(e instanceof Error?e.message:'Model unavailable');}}
 setGroups(groups:string[]){this.groups=new Set(groups);for(const [id,mesh] of this.meshes)mesh.visible=this.groups.has(this.manifest.structures.find(s=>s.id===id)?.group||'');this.invalidate();}
 setPreset(name:string){const m=this.manifest.id;if(name==='exterior')this.setGroups(m==='kidney'?['Capsule']:['Peripheral zone','Central zone','Transition zone','Anterior fibromuscular stroma']);else if(name==='internal')this.setGroups(m==='kidney'?['Outer cortex','Renal columns','Renal pyramids','Renal papillae','Hilum']:['Peripheral zone','Central zone','Transition zone','Anterior fibromuscular stroma']);else if(name==='outflow')this.setGroups(['Renal papillae','Minor calyces','Major calyces','Renal pelvis','Ureter']);else if(name==='ducts')this.setGroups(['Prostatic ducts','Ejaculatory duct','Prostatic utricle','Seminal colliculus','Apex','Base']);else if(name==='context')this.setGroups(['Seminal vesicle','Deferent ducts','Ejaculatory duct']);else this.setGroups(this.manifest.groups);if(name!=='exterior')this.fitVisible();}
 select(id:string){if(this.selected===id)return;const old=this.meshes.get(this.selected);if(old){const materials=Array.isArray(old.material)?old.material:[old.material];for(const mat of materials)(mat as MeshStandardMaterial).emissive.set(0x000000);}this.selected=id;const mesh=this.meshes.get(id);if(mesh){const s=this.manifest.structures.find(item=>item.id===id)!;if(!this.groups.has(s.group))this.setGroups([...this.groups,s.group]);const mats=Array.isArray(mesh.material)?mesh.material:[mesh.material];for(const mat of mats)(mat as MeshStandardMaterial).emissive.set(0x0a3e30);this.onSelect(s);this.fit(new Box3().setFromObject(mesh));}else this.onSelect(null);this.invalidate();}
 setCutaway(enabled:boolean,axis:'horizontal'|'vertical'|'depth',amount:number,reverse:boolean){this.clipping=enabled;this.reverse=reverse;this.cut=Math.max(0,Math.min(1,amount));this.axis.set(axis==='vertical'?1:0,axis==='horizontal'?1:0,axis==='depth'?1:0);this.updatePlane();}
 private updatePlane(){const n=this.axis.clone().multiplyScalar(this.reverse?-1:1);const center=this.bounds.getCenter(new Vector3()),half=this.bounds.getSize(new Vector3()).dot(this.axis)/2,coordinate=center.dot(n)+(this.cut*2-1)*half;this.plane.set(n,-coordinate);for(const mesh of this.meshes.values()){const materials=Array.isArray(mesh.material)?mesh.material:[mesh.material];for(const mat of materials)(mat as MeshStandardMaterial).clippingPlanes=this.clipping?[this.plane]:null;}this.invalidate();}
 fitVisible(){const box=new Box3();for(const mesh of this.meshes.values())if(mesh.visible)box.expandByObject(mesh);if(!box.isEmpty())this.fit(box);}
 private fit(box:Box3){const size=box.getSize(new Vector3()),center=box.getCenter(new Vector3()),distance=Math.max(size.y,size.x/Math.max(this.camera.aspect,.1),.04)/(2*Math.tan(this.camera.fov*Math.PI/360))*1.25+size.z/2;this.controls.target.copy(center);this.camera.position.copy(center).add(new Vector3(0,0,distance));this.controls.update();this.invalidate();}
 private resize=()=>{if(this.disposed)return;const w=Math.max(1,this.host.clientWidth),h=Math.max(1,this.host.clientHeight);this.camera.aspect=w/h;this.camera.updateProjectionMatrix();this.renderer.setSize(w,h);this.invalidate();};private motion=()=>{this.controls.enableDamping=!this.reduced.matches;this.invalidate();};private visibility=()=>{if(!document.hidden)this.invalidate();};private invalidate=()=>{if(!this.frame&&!this.disposed&&!document.hidden)this.frame=requestAnimationFrame(this.render);};
 private render=()=>{this.frame=0;if(this.disposed)return;this.renderer.info.reset();const moving=this.controls.update();this.renderer.render(this.scene,this.camera);Object.assign(this.host.dataset,{drawCalls:String(this.renderer.info.render.calls),triangles:String(this.renderer.info.render.triangles),geometries:String(this.renderer.info.memory.geometries),textures:String(this.renderer.info.memory.textures)});if(moving)this.invalidate();};
 private pointerDown=(e:PointerEvent)=>{this.downAt={x:e.clientX,y:e.clientY};};private click=(e:MouseEvent)=>{if(Math.hypot(e.clientX-this.downAt.x,e.clientY-this.downAt.y)>5)return;const rect=this.renderer.domElement.getBoundingClientRect();this.pointer.set((e.clientX-rect.left)/rect.width*2-1,-(e.clientY-rect.top)/rect.height*2+1);this.raycaster.setFromCamera(this.pointer,this.camera);const hits=this.raycaster.intersectObjects([...this.meshes.values()].filter(m=>m.visible),false);for(const hit of hits){if(this.clipping&&this.plane.distanceToPoint(hit.point)<0)continue;const id=hit.object.userData.lessonId;if(id){this.select(id);return;}}};
 dispose(){this.disposed=true;this.abort.abort();cancelAnimationFrame(this.frame);this.resizeObserver.disconnect();document.removeEventListener('visibilitychange',this.visibility);this.reduced.removeEventListener('change',this.motion);this.controls.dispose();this.renderer.domElement.removeEventListener('pointerdown',this.pointerDown);this.renderer.domElement.removeEventListener('click',this.click);const materials=new Set(),geometries=new Set();for(const root of this.roots)root.traverse(o=>{if(o instanceof Mesh){geometries.add(o.geometry);for(const mat of (Array.isArray(o.material)?o.material:[o.material]))materials.add(mat);}});for(const g of geometries)(g as Mesh['geometry']).dispose();for(const m of materials)(m as MeshStandardMaterial).dispose();this.environment.dispose();this.renderer.dispose();this.renderer.domElement.remove();}
}
