/* SPDX-License-Identifier: MIT. Imported HRA assets retain CC-BY-4.0. */
import fs from 'node:fs/promises';import path from 'node:path';import crypto from 'node:crypto';
import {assets,HRA_REVISION,crosswalkAliases} from './source-lock.mjs';
const sourceDir=process.env.MEDICA_ORGAN_SOURCE_DIR||'/tmp/medica-organ-sources';
const out='public/anatomy-final/lessons';
const digest=b=>crypto.createHash('sha256').update(b).digest('hex');
async function readSource(a){const p=path.join(sourceDir,a.id+'.'+a.kind);let b;try{b=await fs.readFile(p);}catch{const name={'kidney-left':'kidney','renal-corpuscle':'corpuscle','prostate-acinus':'acinus'}[a.id]||a.id;b=await fs.readFile('/tmp/medica-plan-'+name+'.'+a.kind);}if(digest(b)!==a.sha256)throw Error('Source hash changed: '+a.id);return b;}
async function readSidecar(a,kind){const suffix=kind==='metadata'?'meta':'crosswalk';const p=path.join(sourceDir,a.id+'-'+suffix+(kind==='metadata'?'.yaml':'.csv'));try{return await fs.readFile(p);}catch{const names={'kidney-left':'kidney','renal-corpuscle':'corpuscle','prostate-acinus':'acinus'};return fs.readFile('/tmp/medica-plan-'+(names[a.id]||a.id)+'-'+suffix);}}
function parseGLB(buffer){if(buffer.toString('ascii',0,4)!=='glTF'||buffer.readUInt32LE(4)!==2)throw Error('Invalid GLB');let offset=12,json,bin;while(offset<buffer.length){const len=buffer.readUInt32LE(offset),type=buffer.readUInt32LE(offset+4),chunk=buffer.subarray(offset+8,offset+8+len);if(type===0x4e4f534a)json=JSON.parse(chunk.toString());if(type===0x004e4942)bin=Buffer.from(chunk);offset+=8+len;}if(!json||!bin)throw Error('GLB chunks incomplete');return {json,bin};}
function writeGLB(original,json){const src=parseGLB(original);json.asset={...json.asset,copyright:'HuBMAP Human Reference Atlas, CC BY 4.0; Medica metadata-only adaptation. See /anatomy-final/lessons/credits.txt'};const data=Buffer.from(JSON.stringify(json));const padded=Buffer.concat([data,Buffer.alloc((4-data.length%4)%4,0x20)]),bin=src.bin;const total=12+8+padded.length+8+bin.length,b=Buffer.alloc(total);b.write('glTF',0);b.writeUInt32LE(2,4);b.writeUInt32LE(total,8);b.writeUInt32LE(padded.length,12);b.writeUInt32LE(0x4e4f534a,16);padded.copy(b,20);const start=20+padded.length;b.writeUInt32LE(bin.length,start);b.writeUInt32LE(0x004e4942,start+4);bin.copy(b,start+8);return b;}
function metadataValue(s,key){const lines=s.split(/\r?\n/);const i=lines.findIndex(line=>line.startsWith(key+':'));if(i<0)return '';if(/>[-+]?\s*$/.test(lines[i])){const nested=[];for(let j=i+1;j<lines.length&&/^  /.test(lines[j]);j++)nested.push(lines[j].slice(2));return nested.join(' ').trim();}return lines[i].slice(key.length+1).trim().replace(/^['"]|['"]$/g,'');}
function csv(text){const lines=text.replace(/\r/g,'').trim().split('\n');const headings=lines.shift().split(',');return lines.map(line=>{const cols=line.split(',');return Object.fromEntries(headings.map((h,i)=>[h,cols[i]||'']));});}
const staged=[],sources=[],indexes={};await fs.mkdir(out+'/assets',{recursive:true});
for(const a of assets){const original=await readSource(a),rawMeta=await readSidecar(a,'metadata'),rawCrosswalk=await readSidecar(a,'crosswalk');const meta=rawMeta.toString(),crosswalk=csv(rawCrosswalk.toString());let derived=original,nodes=[];
 if(a.kind==='glb'){const {json,bin}=parseGLB(original);nodes=json.nodes.filter(n=>n.mesh!==undefined).map(n=>({name:n.name,label:n.extras?.label||n.name,conceptId:n.extras?.ontologyid==='-'?'':n.extras?.ontologyid||'',nodeType:n.extras?.node_type||'mesh'}));derived=writeGLB(original,json);if(!parseGLB(derived).bin.equals(bin))throw Error('Geometry bytes altered');}
 else {const ids=new Set([...original.toString().matchAll(/\bid="([^"]+)"/g)].map(m=>m[1]));if(/<script|<foreignObject|\son\w+\s*=|https?:\/\//i.test(original.toString().replace(/xmlns(:xlink)?="[^"]+"/g,'')))throw Error('Unsafe SVG: '+a.id);const unmatched=crosswalk.filter(row=>!ids.has(crosswalkAliases[row.node_id]||row.node_id));if(unmatched.length)throw Error('Crosswalk differs: '+a.id+' '+unmatched.map(x=>x.node_id).slice(0,3));indexes[a.id]=[...new Map(crosswalk.map(row=>[row.node_group,row.node_label])).entries()].map(([id,label])=>({id,label:label||id,elementIds:crosswalk.filter(r=>r.node_group===id).map(r=>crosswalkAliases[r.node_id]||r.node_id)}));}
 const file=`${a.id}-${digest(derived).slice(0,12)}.${a.kind}`;await fs.writeFile(out+'/assets/'+file,derived);await fs.writeFile(out+'/assets/'+a.id+'-metadata.yaml',rawMeta);await fs.writeFile(out+'/assets/'+a.id+'-crosswalk.csv',rawCrosswalk);
 const record={id:a.id,kind:a.kind,url:'/anatomy-final/lessons/assets/'+file,bytes:derived.length,sha256:digest(derived),sourceSha256:a.sha256,sourceUrl:a.url,doi:a.doi,license:'CC-BY-4.0',version:a.object.split('/').at(-1),citation:metadataValue(meta,'citation'),citationOverall:metadataValue(meta,'citationOverall'),metadataSha256:digest(rawMeta),crosswalkSha256:digest(rawCrosswalk),nodes};staged.push(record);sources.push(record);
}
const groupFor=name=>name.includes('kidney_capsule')?'Capsule':name.includes('outer_cortex')?'Outer cortex':name.includes('renal_column')?'Renal columns':name.includes('renal_pyramid')?'Renal pyramids':name.includes('renal_papilla')?'Renal papillae':name.includes('hilum')?'Hilum':name.includes('major_calyx')?'Major calyces':name.includes('minor_calyx')?'Minor calyces':name.includes('renal_pelvis')?'Renal pelvis':name.includes('ureter')?'Ureter':name.includes('peripheral_zone')?'Peripheral zone':name.includes('central_zone')?'Central zone':name.includes('transition_zone')?'Transition zone':name.includes('fibromuscular')?'Anterior fibromuscular stroma':name.includes('prostate_duct')?'Prostatic ducts':name.includes('ejaculatory')?'Ejaculatory duct':name.includes('utricle')?'Prostatic utricle':name.includes('seminal_colliculus')?'Seminal colliculus':name.includes('apex')?'Apex':name.includes('base')?'Base':name.includes('seminal_vesicle')?'Seminal vesicle':name.includes('vas_deferens')?'Deferent ducts':'Other source structure';
const makeLesson=(id,side)=>{const assetIds=id==='kidney'?[`kidney-${side}`,`ureter-${side}`]:['prostate'];const items=staged.filter(a=>assetIds.includes(a.id));const structures=items.flatMap(a=>a.nodes.map(n=>({id:`hra:${a.id}:${n.name}`,label:n.label,group:groupFor(n.name),conceptId:n.conceptId,assetId:a.id,nodeName:n.name,nodeType:n.nodeType,representation:'source-3d',reviewState:'pending'})));const svgIds=id==='kidney'?['nephron','renal-corpuscle']:['prostate-acinus'];return {version:1,id,side,title:id==='kidney'?'Kidney':'Prostate',atlasEntryIds:id==='kidney'?['bp-FMA7205','bp-FMA7204']:['za-0fa320e13ac298d5'],reviewState:'pending',sources:items.concat(staged.filter(a=>svgIds.includes(a.id))),modelAssets:items.map(({nodes,...rest})=>rest),diagrams:svgIds.map(i=>({...staged.find(a=>a.id===i),groups:indexes[i]})),structures,groups:[...new Set(structures.map(s=>s.group))],missing:id==='kidney'?['Complete intrarenal vasculature and innervation in 3D','Patient-specific anatomy','Quantitative physiology simulation']:['Complete prostate vascular and nerve networks in 3D','Directly sourced prostatic-urethra mesh','Patient-specific anatomy','Quantitative physiology simulation']};};
for(const side of ['left','right']){await fs.mkdir(out+'/kidney',{recursive:true});await fs.writeFile(`${out}/kidney/${side}.json`,JSON.stringify(makeLesson('kidney',side)));}
await fs.mkdir(out+'/prostate',{recursive:true});await fs.writeFile(out+'/prostate/manifest.json',JSON.stringify(makeLesson('prostate','midline')));
await fs.writeFile(out+'/catalog.json',JSON.stringify({version:1,entries:[{id:'kidney',atlasEntryIds:['bp-FMA7205','bp-FMA7204'],sides:['left','right']},{id:'prostate',atlasEntryIds:['za-0fa320e13ac298d5'],sides:['midline']}]}));
await fs.writeFile(out+'/provenance.json',JSON.stringify({revision:HRA_REVISION,modifications:['GLB copyright metadata inserted; all binary geometry chunks unchanged','SVG crosswalk capitalization aliases documented; originals unchanged'],assets:staged.map(({nodes,...rest})=>rest),crosswalkAliases},null,2));
await fs.writeFile(out+'/coverage.json',JSON.stringify({reviewStatus:'pending',kidney:makeLesson('kidney','left').missing,prostate:makeLesson('prostate','midline').missing},null,2));
await fs.writeFile(out+'/credits.txt',staged.map(a=>`${a.id} — ${a.version} — ${a.license}\n${a.citation}\n${a.citationOverall}\nDOI https://doi.org/${a.doi}\nOriginal ${a.sourceUrl}\nModified: GLB copyright metadata only when applicable; SVG assets original; interactive labels and presentation added by Medica.\nSource SHA-256 ${a.sourceSha256}\nRuntime SHA-256 ${a.sha256}\nLicense https://creativecommons.org/licenses/by/4.0/\n`).join('\n'));
console.log('Organ lesson assets prepared:',staged.length);
